version: "3"

services:
  test:
    build:
      context: .
    volumes:
      - ./watch-this:/test/watch-this
    command: [ "main.py" ]
  async-test:
    build:
      context: .
    volumes:
      - ./watch-this:/test/watch-this
    command: [ "async-main.py" ]
